import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFileSync, existsSync, mkdirSync } from 'node:fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// In dev mode, copy each build into the local test vault so Obsidian (with the
// Hot Reload plugin) picks it up. Skipped if the test vault doesn't exist.
const TEST_VAULT_PLUGIN_DIR = 'test-vault/.obsidian/plugins/watchlist-notes';
const copyToTestVault = {
	name: 'copy-to-test-vault',
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0 || !existsSync('test-vault')) return;
			mkdirSync(TEST_VAULT_PLUGIN_DIR, { recursive: true });
			for (const file of ['main.js', 'manifest.json', 'styles.css']) {
				copyFileSync(file, `${TEST_VAULT_PLUGIN_DIR}/${file}`);
			}
			console.log(`[copy-to-test-vault] copied build to ${TEST_VAULT_PLUGIN_DIR}`);
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	// DEV_BUILD is true in `npm run dev` and false in release builds, so code
	// inside `if (DEV_BUILD)` (developer checks) is left out of released main.js.
	define: { DEV_BUILD: prod ? 'false' : 'true' },
	// The TMDB logo (assets/tmdb-logo.svg) is bundled unchanged as a data URL, so showing it needs no request.
	loader: { '.svg': 'dataurl' },
	outfile: 'main.js',
	minify: prod,
	plugins: prod ? [] : [copyToTestVault],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
